### PR TITLE
Fixed Fortify issues:

### PR DESCRIPTION
**Pull request by charlietritran**
- Risky Resource Management, CWE ID 022

### CODE REVIEW

**Comment by dstenger** [comment]
@keshav-nangare Can you please test this pull request?

**Comment by charlietritran** [comment]
Hi,

I am not working on GEI project any more so I can not test this request.  This will be applied to other pull requests as well under my email address.  Please ignore the pull request if it does not fix for now.

Thank you,
Charlie

Charlie Tran
Leidos
703-249-5150 (H)
571-236-6326(C)
================= !

________________________________

**Comment by keshav-nangare** [comment]
This PR can be ignored as its changes are included into #11. Also the dependency has been updated into the same PR.

**Comment by dstenger** [comment]
PR was replaced by https://github.com/opengeospatial/ets-wfs20-nsg10/pull/11.

**Pull request merged**
